### ISSUE TITLE
Python3 not installing successfully 

### ISSUE THREAD

**Issue by 00indian000** [black-samaritan/LurkerX#1]

**Comment by the-hollowclan** [comment]
Hi there! I've just released the project on GitHub, but please note that this initial release is primarily for testing the installation process via the GitHub repo. The goal is to ensure stability and widespread compatibility before making it ready for general use. I appreciate your interest, but I recommend waiting for a future release that's specifically marked as stable for cloning and usage. A future release of this project is scheduled on August 14, 2024
Thanks for your understanding and support!

**Comment by the-hollowclan** [comment]
The next update will feature Docker support, as well as cross device compatibility. All dependencies will be included automatically when installing LurkerX next update. 
Thanks for your support.

**Comment by the-hollowclan** [comment]
I'm about to make a commit to his repository. The commit fixes the errors in installation of all dependencies of LurkerX, and docker integration of LurkerX. Tonight

**Comment by the-hollowclan** [comment]
Installation issues fixed successfully.
This update will not need any dependencies, LurkerX is now packaged as a compiled binary, currently suitable for Linux platforms. 
Thus, after cloning and installing LurkerX, you can just run the command 'lurkerx' to start it. 
Run the installation file to auto-install LurkerX and you're good to go. Installation file is 'install.sh', as described in the installation guide.
